export const regUrl = 'https://dev-discgolf.herokuapp.com/register'
export const logUrl = 'https://dev-discgolf.herokuapp.com/login'
export const courseUrl = 'https://dev-discgolf.herokuapp.com/courses'
export const userUrl = 'https://dev-discgolf.herokuapp.com/users/current'
export const MAIN_API_URL = 'https://disc-golf-database.herokuapp.com/'
